import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function get_my_role() returns smallint language sql stable as $$ select case when auth.uid()='${id(3)}' then 3 when auth.uid()='${id(2)}' then 2 else 1 end::smallint $$;
create table photos(id uuid primary key,user_id uuid,created_at timestamptz);
create table votes(id uuid primary key default gen_random_uuid(),photo_id uuid,voter_id uuid,created_at timestamptz default now());
create table reservations(id uuid primary key default gen_random_uuid(),user_id uuid,microwave_id uuid,date date,created_at timestamptz default now());
create table microwave_draws(closing_day date primary key,performed_by uuid,assigned_count integer);
create table microwaves(id uuid primary key,nom text,is_active boolean,deleted_at timestamptz);
insert into photos values('${id(10)}','${id(1)}',now()-interval '1 day');
insert into votes(photo_id,voter_id) values('${id(10)}','${id(1)}');
grant insert on votes,reservations to authenticated;`);
const sql=readFileSync(new URL('./cancel-election.sql',import.meta.url),'utf8');
await db.exec(sql);await db.exec(sql);
const {rows:[{day}]}=await db.query("select ((now() at time zone 'Europe/Paris')-interval '10 hours')::date::text as day");
for(const user of [1,2]){
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${id(user)}',false)`);
 await assert.rejects(db.query('select cancel_current_election($1)',[day]));await db.exec('reset role');
}
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${id(3)}',false)`);
await assert.rejects(db.query("select cancel_current_election('2000-01-01')"));
await db.query('select cancel_current_election($1)',[day]);await db.query('select cancel_current_election($1)',[day]);
assert.equal((await db.query('select get_current_election_status() as s')).rows[0].s.cancelled,true);
await assert.rejects(db.query(`insert into votes(photo_id,voter_id) values('${id(10)}','${id(2)}')`));
await assert.rejects(db.query("insert into reservations(date) values($1::date+1)",[day]));
await db.exec('reset role');
assert.equal(Number((await db.query('select count(*) n from votes')).rows[0].n),1);
await db.query("insert into cancelled_elections(voting_day,cancelled_by) values($1::date-1,$2)",[day,id(3)]);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${id(3)}',false)`);
assert.equal((await db.query(`select draw_microwave('${id(3)}') as r`)).rows[0].r.status,'cancelled');
await db.exec('reset role');
await db.query('delete from cancelled_elections where voting_day=$1',[day]);
assert.equal((await db.query('select get_current_election_status() as s')).rows[0].s.cancelled,false);
await db.query("insert into reservations(date) values($1::date+1)",[day]);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${id(3)}',false)`);
await assert.rejects(db.query('select cancel_current_election($1)',[day]));
await db.close();console.log('PASS: permissions, stale period, idempotence, vote blocking, reservation blocking, preserved votes, cancelled draw, prior cancellation does not close current period, existing assignments protected.');
