import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const id1='00000000-0000-4000-8000-000000000001';
const id2='00000000-0000-4000-8000-000000000002';
const imagePath=`${id1}/00000000-0000-4000-8000-000000000003.png`;
const imageUrl=`https://example.supabase.co/storage/v1/object/public/profile-avatars/${imagePath}`;
await db.exec(`
create role anon; create role authenticated;
create schema auth; create schema storage;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
create function storage.foldername(text) returns text[] language sql immutable as $$ select string_to_array($1, '/') $$;
create table profiles(id uuid primary key,pseudo text,avatar_url text,role smallint default 1);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to anon,authenticated;
grant all on storage.objects to anon,authenticated;
create policy legacy_storage_all on storage.objects for all to anon,authenticated using(true) with check(true);
insert into profiles values('${id1}','Alice',null,3),('${id2}','Bob',null,1);
`);
const sql=readFileSync(new URL('./personal-settings.sql',import.meta.url),'utf8');
await db.exec(sql);await db.exec(sql);
await db.exec('set role anon');
await assert.rejects(db.exec("select * from update_my_personal_profile('Intrusion',null,false)"));
await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('profile-avatars','${imagePath}')`));
await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id1}',false)`);
assert.equal((await db.query('select * from get_my_personal_profile()')).rows[0].pseudo,'Alice');
await db.exec("select * from update_my_personal_profile('Alice Nouveau',null,false)");
await assert.rejects(db.exec("select * from update_my_personal_profile('X',null,false)"));
await assert.rejects(db.exec(`select * from update_my_personal_profile('Alice','${imageUrl}',true)`));
await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('profile-avatars','${id2}/other.png')`));
await db.exec(`insert into storage.objects(bucket_id,name) values('profile-avatars','${imagePath}')`);
await db.exec(`select * from update_my_personal_profile('Alice','${imageUrl}',true)`);
assert.equal((await db.query('select * from get_my_personal_profile()')).rows[0].avatar_url,imageUrl);
await db.exec("select * from update_my_personal_profile('Alice Sans Photo',null,true)");
assert.equal((await db.query('select * from get_my_personal_profile()')).rows[0].avatar_url,null);
await db.exec(`select set_config('request.jwt.claim.sub','${id2}',false)`);
await assert.rejects(db.exec(`select * from update_my_personal_profile('Bob','${imageUrl}',true)`));
await db.exec(`delete from storage.objects where name='${imagePath}'`);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await db.exec('reset role');
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
const {rows}=await db.query('select * from profiles order by id');
assert.equal(rows[0].role,3);assert.equal(rows[1].pseudo,'Bob');
await db.close();
console.log('Passed: repeatable migration, own profile only, preserved role, validation, upload ownership, avatar replace/remove, denied anonymous access.');
